// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsHUG-uq_4X3LjH03ZSzImnC4SgGtcRk',
    appId: '1:677909571585:web:da98ae2f41f3178cb13800',
    messagingSenderId: '677909571585',
    projectId: 'sih-app-37c64',
    authDomain: 'sih-app-37c64.firebaseapp.com',
    storageBucket: 'sih-app-37c64.appspot.com',
    measurementId: 'G-LBNT0BJLJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUSck9Jm9SsYPSoUl_7kyAgNJWmqQUkc',
    appId: '1:677909571585:android:e8a53d6f89054e54b13800',
    messagingSenderId: '677909571585',
    projectId: 'sih-app-37c64',
    storageBucket: 'sih-app-37c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7V5AOVf9xVRTxOinMHwBm9owUlAKP8c',
    appId: '1:677909571585:ios:f8c0ecd39e4e84c7b13800',
    messagingSenderId: '677909571585',
    projectId: 'sih-app-37c64',
    storageBucket: 'sih-app-37c64.appspot.com',
    iosBundleId: 'com.example.sihProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk7V5AOVf9xVRTxOinMHwBm9owUlAKP8c',
    appId: '1:677909571585:ios:f8c0ecd39e4e84c7b13800',
    messagingSenderId: '677909571585',
    projectId: 'sih-app-37c64',
    storageBucket: 'sih-app-37c64.appspot.com',
    iosBundleId: 'com.example.sihProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJsHUG-uq_4X3LjH03ZSzImnC4SgGtcRk',
    appId: '1:677909571585:web:81b30ebb068c7457b13800',
    messagingSenderId: '677909571585',
    projectId: 'sih-app-37c64',
    authDomain: 'sih-app-37c64.firebaseapp.com',
    storageBucket: 'sih-app-37c64.appspot.com',
    measurementId: 'G-FK5EERKSKZ',
  );
}
